before_install:
   - sudo apt-get -y install moreutils
   - nvm install 0.10 | ts
install:
  - pip install coveralls | ts
  - tools/travis/setup-$TEST_SUITE | ts
  - tools/clean-venv-cache --travis | ts
cache:
  - apt: false
  - directories:
    - $HOME/phantomjs
    - $HOME/zulip-venv-cache
    - node_modules
    - $HOME/node
env:
  global:
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=hnXUEBKsORKHc8xIENGs9JjktlTb2HKlG
  matrix:
    - TEST_SUITE=frontend
    - TEST_SUITE=backend
    - TEST_SUITE=production
    - TEST_SUITE=py3k
language: python
python:
  - "2.7"
matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=mypy
# command to run tests
script:
  - ./tools/travis/$TEST_SUITE | ts
sudo: required
services:
- docker
addons:
  postgresql: "9.3"
after_success:
  coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
